apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deploy
spec:
  selector:
    matchLabels:
      app: auth-api-deploy
  template:
    metadata:
      labels:
        app: auth-api-deploy
    spec:
      containers:
      - name: auth-api-deploy
        image: telitsynnikita/k8s-flower-store_auth_api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-deploy
spec:
  type: LoadBalancer
  selector:
    app: auth-api-deploy
  ports:
  - port: 8000
    targetPort: 8080